services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    healthcheck:
      test: pg_is_ready -U $POSTGRES_USER
      start_interval: 1s
      start_period: 5s
      interval: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./volume:/app-data